current_vers = 2
num = 6

[info]
lachaise = "A perfect way to write assignments"
theatre = "Create your own script for a play"
basic = "A Basic LaTeX Document"
dictionary = "Create your own dictionary!"
news = "Write your own newspaper article"
code = "Code Documentation Focused"
