current_vers = 3
num = 6

[texcreate]
major = 3
minor = 1
patch = 0

[info]
basic = "A Basic LaTeX Document"
lachaise = "A perfect way to write assignments"
news = "Write your own newspaper article"
code = "Code Documentation Focused"
dictionary = "Create your own dictionary!"
theatre = "Create your own script for a play"
