current_vers = 3
num = 6

[info]
theatre = "Create your own script for a play"
lachaise = "A perfect way to write assignments"
dictionary = "Create your own dictionary!"
basic = "A Basic LaTeX Document"
code = "Code Documentation Focused"
news = "Write your own newspaper article"
