current_vers = 3
num = 6

[texcreate]
major = 3
minor = 1
patch = 0

[info]
basic = "A Basic LaTeX Document"
code = "Code Documentation Focused"
lachaise = "A perfect way to write assignments"
theatre = "Create your own script for a play"
news = "Write your own newspaper article"
dictionary = "Create your own dictionary!"
